### PR TITLE
option to disable cache in http_get_with_cookie()

### LINKED ISSUE #1539: NOT_FOUND_CACHE should not be used by http.processor
To not keep re-looking a dependency that is missing we have implemented a in memory `NOT_FOUND_CACHE`, where if a URL returns 404 once, we store it and do not retry it.

This is done a http helper util level, which is also used in http processor and if upstream returns 404, that too gets cached. 

## Expected Behavior

Since the upstream is getting cookies etc, it may return 404 for some URL meant only for currently viewing user, caching it for all users is wrong. 

## Current Behavior

Everything get's cached, and we have to restart fastn server to purge the in-memory cache. Till that time everyone keeps getting 404 for that URL.

## Possible Solution

We split our utility to have different behaviour for downloading dependencies and for doing http processor. 

## Steps to Reproduce (for bugs)

Configure a http processor to point to any URL that returns 404, fastn will only make one request to that URL. 

## Context

We are working on slides, and are using `get_or_404()` helper to return 404 error in case a row is not found. This workflow is broken as the row may be missing in one request and found in next (as it was created in between, or some permission related thing changed between the two requests).

## Your Environment

- `fastn` Version (I.e, output of `fastn -v`): 0.4.8
- Operating System: Mac
- Web Browser: Safari

### PR DESCRIPTION
**Pull request by siddhantk232**
- disable `NOT_FOUND_CACHE` cache for the `http` processor

Fixes #1539

### CODE REVIEW

File: fastn-core/src/http.rs [hunk 1]
```diff
@@ -513,7 +514,11 @@ pub(crate) async fn http_get_with_cookie(
             res.text().await
         );
         tracing::error!(url = url, msg = message);
-        NOT_FOUND_CACHE.write().insert(url.to_string());
+
+        if use_cache {
+            NOT_FOUND_CACHE.write().insert(url.to_string());
+        }
```
Comment (Arpita-Jaiswal) [inline fastn-core/src/http.rs:520]:
```suggestion
       NOT_FOUND_CACHE.write().insert(url.to_string());
```
We have already checked this condition above.

Comment (siddhantk232) [reply fastn-core/src/http.rs:520]: shouldn't we not insert entries from http processors if the `use_cache` is `false`? This will reduce memory usage

Comment (Arpita-Jaiswal) [reply fastn-core/src/http.rs:520]: I have misread the code. I thought it was inside `if use_cache && NOT_FOUND_CACHE.read().contains(url) {` block. You are right.

**Review by Arpita-Jaiswal — APPROVED** [review]
